spring:
  application:
    name: alatka-batch-example
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.dir}/alatka-batch-example/db/example.db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  batch:
    jdbc:
      initialize-schema: NEVER
    job:
      enabled: false
server:
  port: 8087
alatka:
  batch:
    flow:
      type: database